// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaul9iGoNLe75kL1J2BypHSMH_P36x-Mo',
    appId: '1:1043060740733:web:06b026fde64de6a1061714',
    messagingSenderId: '1043060740733',
    projectId: 'carrentalapp-6ef2a',
    authDomain: 'carrentalapp-6ef2a.firebaseapp.com',
    databaseURL: 'https://carrentalapp-6ef2a-default-rtdb.firebaseio.com',
    storageBucket: 'carrentalapp-6ef2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPdVOKtBztwiloQE5B2J3zb1GNpXVHrU',
    appId: '1:1043060740733:android:ee7d5c660a3d9dd1061714',
    messagingSenderId: '1043060740733',
    projectId: 'carrentalapp-6ef2a',
    databaseURL: 'https://carrentalapp-6ef2a-default-rtdb.firebaseio.com',
    storageBucket: 'carrentalapp-6ef2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGpPvmp_hynTaT3-m7WLfCZxNkrjsWwwk',
    appId: '1:881313758097:ios:9db6a3b5ef833618bab830',
    messagingSenderId: '881313758097',
    projectId: 'project-22093',
    storageBucket: 'project-22093.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGpPvmp_hynTaT3-m7WLfCZxNkrjsWwwk',
    appId: '1:881313758097:ios:9db6a3b5ef833618bab830',
    messagingSenderId: '881313758097',
    projectId: 'project-22093',
    storageBucket: 'project-22093.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzglsnz6b81VmhxD1KSlSkMfIjHML4qJc',
    appId: '1:881313758097:web:7f638afb6a813021bab830',
    messagingSenderId: '881313758097',
    projectId: 'project-22093',
    authDomain: 'project-22093.firebaseapp.com',
    storageBucket: 'project-22093.firebasestorage.app',
    measurementId: 'G-PB0T9KB1WF',
  );

}